protected/modules/admin/controllers/ReviewController.php
<?php

class ReviewController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='/layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow authenticated user to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('@'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','publish'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Review;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Review']))
		{
			$model->attributes=$_POST['Review'];
			if($model->save()) {
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Review']))
		{
			$model->attributes=$_POST['Review'];
			if($model->save()) {
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	public function actionPublish($id)
	{
	    if(Yii::app()->request->isPostRequest)
	    {
			$model=$this->loadModel($id);
		
			// Uncomment the following line if AJAX validation is needed
			// $this->performAjaxValidation($model);
		
			if($model)
			{
				$model->statusId = intval($_GET['statusId']);
				if($model->save()) {
					/* Начисление бонусов за отзыв */
					switch ($model->statusId) {
						case 2:
							if($model->bonus > 0 || empty($model->userId)) {
								break;
							}
							else {
								$user = User::model()->findByPk($model->userId);
								if(is_object($user)) {
									Yii::import('application.controllers.UserController');
									if(UserController::incrementBalance($user, 100)) {
										$model->bonus += 100;
										$model->update();
									}
								}
							}
							break;
					}
				}
			}
	
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		if(!isset($_GET['Review']['statusId'])) $_GET['Review']['statusId'] = 1;
		
		$model = Review::model();
		$model->attributes = Yii::app()->request->getParam(get_class($model));

		$criteria = new CDbCriteria();
		$criteria->with = ['doctor' => ['together' => true,]];
		if($model->statusId != NULL) {
			$criteria->addCondition("statusId = :statusId");
			$criteria->params += array(':statusId' => $model->statusId);
		}
		if($model->userName != NULL) {
			$criteria->addCondition("userName LIKE :userName");
			$criteria->params += array(':userName' => "%".$model->userName."%");
		}
		
		$dataProvider= new CActiveDataProvider($model, array(
			'criteria' => $criteria,
			'pagination' => array(
				'pageSize' => 50,
			),
			'sort' => array(
				'defaultOrder' => 'createDate DESC'
			)
		));
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			'model' => $model,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Review('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Review']))
			$model->attributes=$_GET['Review'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Review the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Review::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Review $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='review-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/admin/controllers/ReviewsController.php
<?php

class ReviewsController extends Controller {

	public function filters() {
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	public function accessRules() {
		return array(
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions' => array('index', 'experts', 'view', 'viewExpert', 'createAddress', 'createExpert', 'deleteAddress', 'deleteExpert'),
				'users' => array('@'),
			),
			array('deny', // deny all users
				'users' => array('*'),
			),
		);
	}

	private $_model;

	public function actionIndex() {
		#$clinic = $this->loadModel();
		$criteria = new CDbCriteria();

		$criteria->with = array(
			'company' => array(
				'together' => true,
			),
			'address' => array(
				'together' => true
			)
		);
		#$criteria->addCondition('status <> -1');
		$model = RaitingCompanyUsers::model();
		$model->company = Company::model();
		$model->attributes = Yii::app()->request->getParam(get_class($model));
		$companyName = Yii::app()->request->getParam('Company')['name'];
		
		if($companyName) {					
			$model->company->name = $companyName;
			$criteria->compare('company.name',$companyName,true);
		}
		if($model->answer == 1) {
			$criteria->addCondition("t.answer <> ''");
		} elseif($model->answer == 2) {
			$criteria->addCondition("t.answer = ''");
		}
		$criteria->compare('t.status',$model->status);
				
		$dataProvider = new CActiveDataProvider($model, array(
			'criteria' => $criteria,
			'pagination' => array(
				'pageSize' => 50,
			),
			'sort' => array(
				'defaultOrder' => 'status ASC,date DESC'
			)
		));

		$this->render('index', array(
			'dataProvider' => $dataProvider,
			'model' => $model
			
		));
	}

	public function actionExperts() {
		#$clinic = $this->loadModel();
		$criteria = new CDbCriteria();

		$criteria->with = array(
			'doctor' => array(
				'together' => true
			)
		);

		$dataProvider = new CActiveDataProvider('RaitingDoctorUsers', array(
			'criteria' => $criteria,
			'pagination' => array(
				'pageSize' => 30,
			),
			'sort' => array(
				'defaultOrder' => 'date DESC'
			)
		));


		$this->render('experts', array('dataProvider' => $dataProvider));
	}

	public function actionCreateAddress() {
		$model = new RaitingCompanyUsers();
		$type = TypeOfCompanyRaitingUsers::model()->findAll();
		$types = CHtml::listData($type, 'id', 'name');

		$criteria = new CDbCriteria();
		$criteria->select = 'id,link,street,houseNumber';
		$criteria->with = [
			'company' => [
				'select' => 'id,link,name',
				'scopes' => 'clinicByAddress',
				'with' => [
					'companyType' => array(
						'select' => 'id,name',
					),
				]
			]
		];
		$criteria->order = 'company.name ASC,t.name ASC';
		$criteria->compare('t.cityId', (new Search())->cityId);
		$criteria->compare('companyType.isMedical', 1);
		$criteria->addNotInCondition('companyType.id', Address::$arrGMU);
		$addresses = Address::model()->findAll($criteria);

		$listData = [];
		foreach ($addresses as $address) {
			$listData[$address->id] = $address->company->name . ' на ' . $address->street . ', ' . $address->houseNumber;
		}


		$post = Yii::app()->request->getParam(get_class($model));
		if ($post) {
			$model->attributes = $post;
			$model->grades = $post['grades'];
			$model->companyId = Address::model()->findByPk($model->addressId)->ownerId;


			if ($model->save()) {
				foreach ($model->grades as $key => $value) {
					$companyValue = new RaitingCompanyValue();
					$companyValue->typeOfCompanyRaitingUsersId = $key;
					$companyValue->raitingCompanyUsersId = $model->id;
					$companyValue->value = $value;
					$companyValue->save();
				}

				Yii::app()->user->setFlash('registrySuccess', 'Отзыв успешно добавлен');
				$this->redirect(array('reviews/index'));
			}
		}
		$this->render('createAddress', [
			'model' => $model,
			'types' => $types,
			'listData' => $listData
		]);
	}

	public function actionCreateExpert() {
		
		$model = new RaitingDoctorUsers();
		$type = TypeOfDoctorRaitingUsers::model()->findAll();
		$types = CHtml::listData($type, 'id', 'name');

		$criteria = new CDbCriteria();
		$criteria->together = true;
		$criteria->with = [
			'currentPlaceOfWork' => [
				'together' => true,
				'select' => 'id,companyId',
				'with' => [
					'address' => [
						'select' => false,
						'together' => true,
					],
					'company' => [
						'together' => true,
						'select' => 'id,name,link',
					]
				],
			],
		];
		$criteria->select = 'name,id';
		$criteria->group = '`t`.`id`';
		
		$criteria->compare('address.cityId', (new Search())->cityId);
		$doctors = Doctor::model()->findAll($criteria);
		
		$listData = [];
		foreach ($doctors as $key=>$d) {
			$listData[$d->id] = $d->currentPlaceOfWork->company->name . ' - ' . $d->name;				
		}


		$post = Yii::app()->request->getParam(get_class($model));
		if ($post) {
			$model->attributes = $post;
			$model->grades = $post['grades'];
			#$model->companyId = Address::model()->findByPk($model->addressId)->ownerId;
			
			if ($model->save()) {
				foreach ($model->grades as $key => $value) {				
					$companyValue = new RaitingDoctorValue();
					$companyValue->typeOfDoctorRaitingUsersId = $key;
					$companyValue->raitingDoctorUsersId = $model->id;
					$companyValue->value = $value;
					$companyValue->save();
				}
				Yii::app()->user->setFlash('registrySuccess', 'Отзыв успешно добавлен');
				$this->redirect(array('reviews/experts'));
			}			
		}

		$this->render('createExpert', [
			'model' => $model,
			'types' => $types,
			'listData' => $listData
		]);
	}

	public function actionDeleteAddress($id) {
		$model = RaitingCompanyUsers::model()->findByPk($id);
		foreach ($model->raitingCompanyValues as $v) {
			$v->delete();
		}
		$model->delete();
	}
	
	public function actionDeleteExpert($id) {
		$model = RaitingDoctorUsers::model()->findByPk($id);
		foreach ($model->raitingDoctorValues as $v) {
			$v->delete();
		}
		$model->delete();
	}

	public function actionView($id) {
		$model = new RaitingCompanyUsers('answer');


		if ($attr = Yii::app()->request->getParam(get_class($model))) {

			if (is_array($attr)) {
				$comment = $model->findByPk($id);

				$comment->attributes = $attr;

				if ($comment->save()) {
					Yii::app()->user->setFlash('success', 'Данные успешно сохранены');
					$this->redirect('index');
				}
			}
		}

		$this->render('answer', array(
			'model' => $this->loadModelCompanyComment($id),
		));
	}

	public function actionViewExpert($id) {
		$model = new RaitingDoctorUsers('answer');


		if ($attr = Yii::app()->request->getParam(get_class($model))) {

			if (is_array($attr)) {
				$comment = $model->findByPk($id);

				$comment->attributes = $attr;

				if ($comment->save()) {
					Yii::app()->user->setFlash('success', 'Данные успешно сохранены');
					$this->redirect('experts');
				}
			}
		}

		$this->render('answer', array(
			'model' => $this->loadModelExpertComment($id),
			'viewExpert' => 1,
		));
	}

	public function loadModelCompanyComment($id) {
		$this->_model = RaitingCompanyUsers::model()->findByPk($id);

		if ($this->_model === null)
			throw new CHttpException(404, 'The requested page does not exist.');
		return $this->_model;
	}

	public function loadModelExpertComment($id) {
		$this->_model = RaitingDoctorUsers::model()->findByPk($id);

		if ($this->_model === null)
			throw new CHttpException(404, 'The requested page does not exist.');
		return $this->_model;
	}

	// Uncomment the following methods and override them if needed
	/*
	  public function filters()
	  {
	  // return the filter configuration for this controller, e.g.:
	  return array(
	  'inlineFilterName',
	  array(
	  'class'=>'path.to.FilterClass',
	  'propertyName'=>'propertyValue',
	  ),
	  );
	  }

	  public function actions()
	  {
	  // return external action classes, e.g.:
	  return array(
	  'action1'=>'path.to.ActionClass',
	  'action2'=>array(
	  'class'=>'path.to.AnotherActionClass',
	  'propertyName'=>'propertyValue',
	  ),
	  );
	  }
	 */
}

protected/modules/admin/views/review/_form.php
<?php
/* @var $this ReviewController */
/* @var $model Review */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'review-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'companyId'); ?>
		<?php echo $form->textField($model,'companyId',array('size'=>36,'maxlength'=>36)); ?>
		<?php echo $form->error($model,'companyId'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'addressId'); ?>
		<?php echo $form->textField($model,'addressId',array('size'=>36,'maxlength'=>36)); ?>
		<?php echo $form->error($model,'addressId'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'appointmentToDoctorsId'); ?>
		<?php echo $form->textField($model,'appointmentToDoctorsId',array('size'=>36,'maxlength'=>36)); ?>
		<?php echo $form->error($model,'appointmentToDoctorsId'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'doctorId'); ?>
		<?php echo $form->textField($model,'doctorId',array('size'=>36,'maxlength'=>36)); ?>
		<?php echo $form->error($model,'doctorId'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'userId'); ?>
		<?php echo $form->textField($model,'userId',array('size'=>36,'maxlength'=>36)); ?>
		<?php echo $form->error($model,'userId'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'userName'); ?>
		<?php echo $form->textArea($model,'userName',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'userName'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'userPhone'); ?>
		<?php echo $form->textField($model,'userPhone',array('size'=>60,'maxlength'=>150)); ?>
		<?php echo $form->error($model,'userPhone'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'reviewText'); ?>
		<?php echo $form->textArea($model,'reviewText',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'reviewText'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'answerText'); ?>
		<?php echo $form->textArea($model,'answerText',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'answerText'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'createDate'); ?>
		<?php echo $form->textField($model,'createDate'); ?>
		<?php echo $form->error($model,'createDate'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'statusId'); ?>
		<?php echo $form->textField($model,'statusId'); ?>
		<?php echo $form->error($model,'statusId'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'ratingDoctor'); ?>
		<?php echo $form->textField($model,'ratingDoctor'); ?>
		<?php echo $form->error($model,'ratingDoctor'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'ratingClinic'); ?>
		<?php echo $form->textField($model,'ratingClinic'); ?>
		<?php echo $form->error($model,'ratingClinic'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'confirmCode'); ?>
		<?php echo $form->textField($model,'confirmCode',array('size'=>12,'maxlength'=>12)); ?>
		<?php echo $form->error($model,'confirmCode'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/modules/admin/views/review/_search.php
<?php
/* @var $this ReviewController */
/* @var $model Review */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'companyId'); ?>
		<?php echo $form->textField($model,'companyId',array('size'=>36,'maxlength'=>36)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'addressId'); ?>
		<?php echo $form->textField($model,'addressId',array('size'=>36,'maxlength'=>36)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'appointmentToDoctorsId'); ?>
		<?php echo $form->textField($model,'appointmentToDoctorsId',array('size'=>36,'maxlength'=>36)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'doctorId'); ?>
		<?php echo $form->textField($model,'doctorId',array('size'=>36,'maxlength'=>36)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'userId'); ?>
		<?php echo $form->textField($model,'userId',array('size'=>36,'maxlength'=>36)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'userName'); ?>
		<?php echo $form->textArea($model,'userName',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'userPhone'); ?>
		<?php echo $form->textField($model,'userPhone',array('size'=>60,'maxlength'=>150)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'reviewText'); ?>
		<?php echo $form->textArea($model,'reviewText',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'answerText'); ?>
		<?php echo $form->textArea($model,'answerText',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'createDate'); ?>
		<?php echo $form->textField($model,'createDate'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'statusId'); ?>
		<?php echo $form->textField($model,'statusId'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'ratingDoctor'); ?>
		<?php echo $form->textField($model,'ratingDoctor'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'ratingClinic'); ?>
		<?php echo $form->textField($model,'ratingClinic'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'confirmCode'); ?>
		<?php echo $form->textField($model,'confirmCode',array('size'=>12,'maxlength'=>12)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/modules/admin/views/review/index.php
<?php
/* @var $this ReviewController */
/* @var $dataProvider CActiveDataProvider */
$this->breadcrumbs=array(
	'Reviews',
);

$this->menu=array(
	array('label'=>'Create Review', 'url'=>array('create')),
	array('label'=>'Manage Review', 'url'=>array('admin')),
);
?>
<style>
.table {
	max-width: none;
}
</style>

<h1>Отзывы пациентов</h1>

<?php

/*
$this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
));
*/
$this->widget('zii.widgets.grid.CGridView', array(
	'dataProvider' => $dataProvider,
	'filter' => $model,
	'id' => 'review-list',
	'summaryText' => '',
	'itemsCssClass' => 'table table-striped table-bordered table-condensed',
	'columns' => array(
		[
			'name' => 'createDate',
			'header' => 'Дата',
			'value' => '$data->createDate',
			'htmlOptions' => [
				'style'=>'width:80px'
			],
			'filter' => false,
		],
		[
			'name' => 'doctorId',
			'header' => 'Врач',
			'value' => function($data) {
				$absoluteLink = Yii::app()->request->getParam('absoluteLink',false) ? MyTools::url_origin($_SERVER, false) : "";
				$subdomain = $data->doctor->currentPlaceOfWork->address->city->subdomain;
				$domain = City::getRedirectUrl($subdomain, $data->doctor->currentPlaceOfWork->address->samozapis, "");
				$doctorLink = $absoluteLink . (($domain !== MyTools::url_origin($_SERVER, false)) ? $domain : "") . Yii::app()->createUrl('doctor/view', array('linkUrl' => $data->doctor->linkUrl, 'companyLinkUrl' => $data->doctor->currentPlaceOfWork->address->company->linkUrl, 'addressLinkUrl' => $data->doctor->currentPlaceOfWork->address->linkUrl));

				return CHtml::link($data->doctor->name, $doctorLink, array("target"=>"_blank"));
			},
			'type' => 'raw',
			'htmlOptions' => [
				'style'=>'width:120px'
			],
			'filter' => false,
		],
		[
			'name' => 'userName',
			'header' => 'Отправитель',
			'value' => '$data->userName',
			'htmlOptions' => [
				'style'=>'width:120px'
			],
			'filter' => CHtml::textField('Review[userName]', $model->userName, [
				'autofocus' => 'true'
				]
			),
		],
		[
			'name' => 'ratingDoctor',
			'header' => 'Оценка врача',
			'value' => '$data->ratingDoctor',
			'htmlOptions' => [
				'style'=>'width:50px'
			],
			'filter' => false,
		],
		[
			'name' => 'ratingClinic',
			'header' => 'Оценка клиники',
			'value' => '$data->ratingClinic',
			'htmlOptions' => [
				'style'=>'width:50px'
			],
			'filter' => false,
		],
		[
			'name' => 'reviewText',
			'header' => 'Отзыв',
			'value' => '$data->reviewText',
			'filter' => false,
		],
		[
			'name' => 'answerText',
			'header' => 'наличие ответа',
			'value' => '$data->answerText ? "да" : "нет"',
			'htmlOptions' => [
				'style'=>'width:50px'
			],
			'filter' => false,
		],
		[
			'name' => 'statusId',
			'header' => 'Статус',
			'value' =>  '$data->statusId==0 ? "не опубликован (телефон не подтвержден) " : 
						($data->statusId==1 ? "не опубликован (телефон подтвержден)" : 
						($data->statusId==2 ? "опубликован" : 
						($data->statusId==3 ? "отклонен" : "не задан")))',
			'htmlOptions' => [
				'style'=>'width:100px'
			],
			'filter' => CHtml::dropDownList('Review[statusId]', Yii::app()->request->getParam('Review')['statusId'], [''=>'Все',3=>'отклонен',2=>'опубликован',1=>'не опубликован (телефон подтвержден)',0=>'не опубликован (телефон не подтвержден)'])
		],
		[
			'class' => 'CButtonColumn',
			'header' => 'Действие',
			'template' => '{public}{reject}{update}',
			'buttons' => [
				'public' => [
					'url' => 'CHtml::normalizeUrl(array("review/publish","id"=>$data->id,"statusId"=>2))',
					'label' => 'Опубликовать',			
					'imageUrl' => false,
					'options' => [
						'class'=>'btn btn-success',
						'style' => 'height:20px; width: 80%;',
					],
					'click'=>"function(){
						$.fn.yiiGridView.update('review-list', {
							type:'POST',
							url:$(this).attr('href'),
							success:function(text,status) {
								$.fn.yiiGridView.update('review-list');
							}
						});
						return false;
					}",
				],
				'reject' => [
					'url' => 'CHtml::normalizeUrl(array("review/publish","id"=>$data->id,"statusId"=>3))',
					'label' => 'Отклонить',			
					'imageUrl' => false,
					'options' => [
						'class'=>'btn btn-danger',
						'style' => 'height:20px; width: 80%;',
					],
					'click'=>"function(){
						$.fn.yiiGridView.update('review-list', {
							type:'POST',
							url:$(this).attr('href'),
							success:function(text,status) {
								$.fn.yiiGridView.update('review-list');
							}
						});
						return false;
					}",
				],
				'update' => [
					'url' => 'CHtml::normalizeUrl(array("review/update","id"=>$data->id))',
					'label' => 'Редактировать',			
					'imageUrl' => false,
					'options' => [
						'class'=>'btn btn-primary',
						'style' => 'height:20px; width: 80%;',
					]
				],
			],
			'htmlOptions' => [
				'style'=>'width:100px'
			],
		],
	)
));

?>