protected/modules/adminAll/controllers/ExpertsController.php
<?php

class ExpertsController extends AdminAllController
{

	public function actionIndex()
	{		
	
		header("Access-Control-Allow-Origin: *");
		$clinic = $this->loadModel();
		
		$criteria = new CDbCriteria();

		$criteria->with = array(
			'importPlaceOfWork',
			'importPlaceOfWork.address',
		);

		$criteria->compare('`address`.`id`', $clinic->id);

		$dataProvider = new CActiveDataProvider('Doctor', array(
			'criteria'	 => $criteria,
			'pagination' => array(
				'pageSize' => 30,
			),			
		));
		
		/*DOCTOR*/
		$oDoctors = new Doctor('search');
		$oDoctors->attributes = Yii::app()->request->getParam(get_class($oDoctors));
		
		$doctorSpecialties = new DoctorSpecialty('search');
		$doctorSpecialties->unsetAttributes();
		
		$oDoctors->doctorSpecialty = $doctorSpecialties;
		$arr=Yii::app()->request->getParam('DoctorSpecialty');
		if ($arr['name']) {
			$oDoctors->doctorSpecialty->name = $_GET['DoctorSpecialty']['name'];
		}
		/*DOCTOR*/
		
		
		/*AGR_DOCTOR*/
		$oAgrDoctors = new AgrDoctor('search');
		$oAgrDoctors->attributes = Yii::app()->request->getParam(get_class($oAgrDoctors));	
		
		$doctorSpecialties = new DoctorSpecialty('search');
		$doctorSpecialties->unsetAttributes();		
		
		$oAgrDoctors->doctorSpecialty = $doctorSpecialties;
		$arr=Yii::app()->request->getParam('DoctorSpecialty');
		if ($arr['name']) {
			$oAgrDoctors->doctorSpecialty->name = $_GET['DoctorSpecialty']['name'];
		}
		/*AGR_DOCTOR*/
		
		
		$this->render('index', array('model' => $clinic, 'doctors' => $clinic->doctors, 'dataProvider' => $dataProvider, 'oDoctors' => $oDoctors, 'oAgrDoctors'=>$oAgrDoctors));
	}

	public function actionAdd()
	{		
		
		
		
		$model = new AgrDoctor('insert');

		$attr = Yii::app()->request->getParam(get_class($model));
		$oErorrs = array();
	
		if ($attr) {
			//var_dump($attr);
			$date = strtotime($attr['birthday']);
			
			
			if(!$date) {
				$attr['birthday'] = "0000-00-00 00:00:00";
			} else {
				$attr['birthday'] = date("Y-m-d",  $date);
			}
			$model->attributes = $attr;
			
			//$model->id = $_SESSION['doctorIdTemp'] = !empty($_SESSION['doctorIdTemp']) ? $_SESSION['doctorIdTemp'] : md5(Yii::app()->user->id . time());

			$model->name = $model->surName . ' ' . $model->firstName . ' ' . $model->fatherName;

			$model->scientificTitle	= $attr['scientificTitle'] ? $attr['scientificTitle'] : null;			
			
			if($attr['scientificDegrees'] && reset($attr['scientificDegrees'])) {
				$model->scientificDegrees	 = $attr['scientificDegrees'];				
			} else {				
				DoctorScientificDegree::model()->deleteAllByAttributes(array('doctorId' => $model->id));
			}
			if(($model->scientificDegrees[0] != 'a0e63271-e562-11e1-8649-60fb4275079e') && ($model->scientificTitle == '81e0f6b8-947f-11e2-856f-e840f2aca94f')) {				
				$oErorrs['scientificTitle'] = "Профессором может быть только доктор медицинских наук.";
			}
		
			

			$model->photo = CUploadedFile::getInstance($model, 'photo');
			
			/*if(empty($model->scientificDegrees) || empty($model->scientificDegrees[0])) {
				$oErorrs['scientificDegrees'] = "Необходимо заполнить поле Ученая степень.";
			}*/
			/*if(empty($attr['doctorEducations'])) {
				$oErorrs['doctorEducations'] = "Необходимо заполнить поле Учебное заведение.";
			}*/
			if(empty($attr['specialtyOfDoctors'])) {
				$oErorrs['specialtyOfDoctors'] = "Необходимо заполнить поле Специальность.";
			}

			
			//print_r($oErorrs);
			if (!Yii::app()->request->isAjaxRequest & $model->validate() && count($oErorrs) === 0) {		
				
				$currentLink = Yii::app()->db->createCommand()->
						select("max(`link`)")->
						from(Doctor::model()->tableName())->
						queryScalar();
				$secondLink = Yii::app()->db->createCommand()->
						select("max(`link`)")->
						from(AgrDoctor::model()->tableName())->
						queryScalar();
				if((int)$secondLink>(int)$currentLink) {
					$currentLink = $secondLink;
				}
				$currentLink = intval($currentLink);
				$currentLink++;
				$model->link = str_pad($currentLink, 9, '0', STR_PAD_LEFT);
				
				if($model->save()) {
					
					$model->setSpecialtyOfDoctors($attr['specialtyOfDoctors']);
					$model->setDoctorEducations($attr['doctorEducations']);
					$model->setCurrentPlaceOfWork($this->loadModel());


					if ($model->photo instanceof CUploadedFile) {
						$model->photo->saveAs($model->photoPath);
					}
					//unset($_SESSION['doctorIdTemp']);
					$this->redirect(array('price', 'link'=>$model->link));
				}
				
			}
			else {					
				if (!empty($oErorrs)) {
					
					foreach ($oErorrs as $label=>$error) {						
						$model->addError($label, $error);
					}
				} else {
					/*
					if(!empty($attr['specialtyOfDoctors'])) {
						$model->setSpecialtyOfDoctors($attr['specialtyOfDoctors']);
					}
					if(!empty($attr['doctorEducations'])) {
						$model->setDoctorEducations($attr['doctorEducations']);
					}*/
				}
				
				$this->performAjaxValidation($model);					
			}
			
			$this->performAjaxValidation($model);
			
		}

		$this->render('add', array('model' => $model));
	}

	public function actionUpdate($link)
	{

		$model = Doctor::model()->findByAttributes(array('link' => $link));
		/* @var $model Doctor */
		
		$attr = Yii::app()->request->getParam(get_class(AgrDoctor::model()));
		
			
			
		
		$agr_model= AgrDoctor::model()->findByAttributes(array('link' => $link));
		if(!$agr_model && !$model) {
			$this->redirect(array('experts/index'));
		}
		
		if(!$agr_model) {
			$agr_model = new AgrDoctor();
			$agr_model->photo = $model->photo;
			$agr_model->attributes = $model->attributes;
			$agr_model->specialtyOfDoctors=$model->specialtyOfDoctors;
			$agr_model->doctorEducations=$model->doctorEducations;
			$agr_model->scientificDegrees=$model->scientificDegrees;
			$agr_model->scientificTitle=$model->scientificTitle;			
		}				
		$agr_model->scenario = 'update';
		
		if(Yii::app()->user->model->companyId <> $model->currentPlaceOfWork->companyId) {
			$this->redirect("index");
		}
		
		if ($attr) {
			
			//echo Yii::app()->dateFormatter->formatDateTime(strtotime($action->start), 'short', null);
			
			//$date = date_parse($attr['birthday']);#
			
			
			$date = strtotime($attr['birthday']);
			
			if(!$date) {
				$date = strtotime("0000-00-00 00:00:00");
				$attr['birthday'] = "0000-00-00 00:00:00";
			} else {
				$attr['birthday'] = date("Y-m-d",  $date);
			}
			//$attr['birthday'] = $date['year'] .'-'. $date['month'] . '-' . $date['day'];
			
			$agr_model->attributes = $attr;
			
			$agr_model->name = $agr_model->surName . ' ' . $agr_model->firstName . ' ' . $agr_model->fatherName;
			if($date == strtotime($model->birthday)
					&&	$attr['surName']==$model->surName
					&&	$attr['firstName']==$model->firstName
					&&  $attr['fatherName']==$model->fatherName
					&&  $attr['experience']==$model->experience
					&&  $attr['sexId'] == $model->sexId
					&&  $attr['description'] == $model->description) {
				$deleteAgr=true;
			}
			
			
			$agr_model->scientificTitleId	= $attr['scientificTitle'] ? $attr['scientificTitle'] : 'a6f95ab7-441e-4b2b-91a2-ab3faf548d8e';
			
			
			if($attr['scientificDegrees'] && reset($attr['scientificDegrees'])) {		
				
				
				$agr_model->scientificDegrees = array(0=>$attr['scientificDegrees'][0]);		
				#$agr_model->scientificDegrees[0]->id = $attr['scientificDegrees'][0];		
				
			
				
			} else {				
				AgrDoctorScientificDegree::model()->deleteAllByAttributes(array('doctorId' => $agr_model->id));
				DoctorScientificDegree::model()->deleteAllByAttributes(array('doctorId' => $agr_model->id));
				#var_dump($model->scientificDegrees[0]);die();				
			}
			
			if(( ($agr_model->isNewRecord ? $agr_model->scientificDegrees[0] : $agr_model->scientificDegrees[0]->id) != 'a0e63271-e562-11e1-8649-60fb4275079e') 
					&& ($agr_model->scientificTitleId == '81e0f6b8-947f-11e2-856f-e840f2aca94f')) {				
				$oErorrs['scientificTitle'] = "Профессором может быть только доктор медицинских наук.";
			}
			
			/*if(empty($model->scientificDegrees) || empty($model->scientificDegrees[0])) {
				$oErorrs['scientificDegrees'] = "Необходимо заполнить поле Ученая степень.";
			}*/
			/*if(empty($attr['doctorEducations'])) {
				$oErorrs['doctorEducations'] = "Необходимо заполнить поле Учебное заведение.";
			}*/
			if(empty($attr['specialtyOfDoctors'])) {
				$oErorrs['specialtyOfDoctors'] = "Необходимо заполнить поле Специальность.";
			}

			
			if (!Yii::app()->request->isAjaxRequest & $agr_model->validate() && count($oErorrs) === 0) {
               
				
					
					if($deleteAgr ) {
						if(!$agr_model->isNewRecord) {
							$agr_model->delete();	
						}			
						if(!$oErorrs['scientificTitle']) {
							$model->scientificTitle = $attr['scientificTitle'] ? $attr['scientificTitle'] : 'a6f95ab7-441e-4b2b-91a2-ab3faf548d8e';	
							if($attr['scientificDegrees'][0]) {
								$model->scientificDegrees[0] = $attr['scientificDegrees'][0];
							} else {
								$model->scientificDegrees = [];
							}
							
						}
						
						if($model->save()){
							
							$model->setSpecialtyOfDoctors($attr['specialtyOfDoctors']);						
							$model->setDoctorEducations($attr['doctorEducations']);					
							$model->setCurrentPlaceOfWork($this->loadModel());
						}
						#$model->save();
					} else {									
						if($agr_model->save()) {		
							
							$agr_model->setSpecialtyOfDoctors($attr['specialtyOfDoctors']);							
							$agr_model->setDoctorEducations($attr['doctorEducations']);							
							$agr_model->setCurrentPlaceOfWork($this->loadModel());
							
						}					
					}
				
				
				
				
				

				$this->redirect(array('price', 'link'=>$agr_model->link));
				
			} else {
				if (!empty($oErorrs)) {
					
					foreach ($oErorrs as $label=>$error) {
						$agr_model->addError($label, $error);
					}
					
				} else {
					/*
					if(!empty($attr['specialtyOfDoctors'])) {
						$agr_model->setSpecialtyOfDoctors($attr['specialtyOfDoctors']);
					}
					if(!empty($attr['doctorEducations'])) {

protected/modules/adminAll/controllers/NewsController.php
<?php

class NewsController extends AdminAllController {

	private $_model;

	public function filters() {
		return array(
			'postOnly + delete', // we only allow deletion via POST request
			'accessControl', // perform access control for CRUD operations
		);
	}

	public function accessRules() {
		return array(
			array('allow', 
				'actions' => array('index', 'add', 'update', 'delete'),
				'users' => array('@'),
			),
			array('deny', // deny all users
				'users' => array('*'),
			),
		);
	}

	public function actionIndex() {
		$clinic = $this->loadModel();
		$criteria = new CDbCriteria();

		$criteria->compare('`clinicId`', $clinic->id);

		$dataProvider = new CActiveDataProvider('News', array(
			'criteria' => $criteria,
			'pagination' => array(
				'pageSize' => 30,
			),
			'sort' => array(
				'defaultOrder' => 'publish DESC,datePublications DESC'
			)
		));


		$this->render('index', array('dataProvider' => $dataProvider));
	}

	public function actionAdd() {
		$model = new News();

		if ($attr = Yii::app()->request->getParam(get_class($model))) {
			$model->attributes = $attr;

			$typeId = TypeNews::model()->clinic()->find()->id;
			$model->typeNewsId = $typeId;

			$model->publish = 0;
			$model->Date = date("Y-m-d H:i:s", time());
			$model->clinicId = $this->loadModel()->id;
			if ($model->save()) {
				Yii::app()->user->setFlash('success', 'Данные успешно сохранены');
				$this->redirect('index');
			}
		}

		$this->render('update', array(
			'model' => $model
		));
	}

	public function actionUpdate($id) {
		$model = $this->loadModelNews($id);

		if ($attr = Yii::app()->request->getParam(get_class($model))) {

			if (is_array($attr)) {

				$temp = $model->attributes;
				$model->attributes = $attr;

				$typeId = TypeNews::model()->clinic()->find()->id;
				$model->typeNewsId = $typeId;

				/* Если нет изменений - не сохраняем модель */
				$tmp1 = array_diff($temp, $model->attributes);
				$tmp2 = array_diff($model->attributes, $temp);

				$model->publish = 0;
				$save = true;
				if (!$tmp1 && !$tmp2) {
					$save = false;
				}

				if ($save) {

					if ($model->save()) {
						Yii::app()->user->setFlash('success', 'Данные успешно сохранены');
						$this->redirect('index');
					}
				} else {
					$this->redirect('index');
				}
			}
		}

		$this->render('update', array(
			'model' => $model
		));
	}

	public function actionDelete($id) {
		$this->loadModelNews($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if (!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
	}

	public function loadModelNews($id) {
		$this->_model = News::model()->findByPk($id);

		if ($this->_model === null)
			throw new CHttpException(404, 'The requested page does not exist.');
		return $this->_model;
	}

}

protected/modules/adminAll/views/experts/import.php
<script>	
	$(document).ready(function() {
		$(".all_clients .expert").live('click',function() {
			$(this).hide();
			$(this).removeClass("searchReady");
			var cid = $(this).attr('data-cid');
			$.ajax({
	                url: '/adminAll/ajax/addExpert',
	                data: ({
	                    'doctor': cid
	                }),
	                dataType: 'JSON',
	                type: "GET",
	                success: function(response) {                    
	                   console.log(response);
	                },
	        });
			$(".checked_clients").append('<div data-cid="'+cid+'" class="pexpert">'+$(this).html()+'</div>');
		});
		
		$(".checked_clients .pexpert").live('click',function() {	
			
			var cid = $(this).attr('data-cid');
			$.ajax({
	                url: '/adminAll/ajax/removeExpert',
	                data: ({
	                    'doctor': cid
	                }),
	                dataType: 'JSON',
	                type: "GET",
	                success: function(response) {                    
	                   console.log(response);
	                },
	        });
			$(".expert[data-cid="+cid+"]").show();
			$(".expert[data-cid="+cid+"]").addClass("searchReady");
			$(this).remove();
		});
		
		document.getElementById("searchExperts").oninput = function() {			
			var txt  = $("#searchExperts").val().toLowerCase();
			
			if(txt) {		
				setTimeout(function() {					
					if(txt == $("#searchExperts").val().toLowerCase()) {						
						$(".searchReady").hide();
						$(".searchReady").each(function() {					
							var rowText = $(this).find("span").html().toLowerCase();
							var ind = rowText.indexOf(txt);
							if(ind != -1) {
								$(this).show();
							} 
						});
					}
				},250);				
			} else {
				$(".searchReady").show();
			}
		}
	});
	
</script>
<h3>Импорт врачей из другого адреса клиники:</h3>

<div class="flash-notice" style="width:325px;">
	Список выбранных специалистов сохраняется автоматически
</div>
<input placeholder="Введите имя специалиста" type="text" id="searchExperts" class="custom-text searchExperts">
<p class="picked_doctors_text">Выбранные специалисты</p>
<div class="both"></div>
<div class="clients">
	<div class="all_clients">
		<?php if($doctors): ?>
			<?php foreach($doctors as $c): ?>
			<div data-cid="<?=$c->link?>" <?= in_array($c->id, $ids) ? 'class="expert" style="display:none"' : 'class="expert searchReady" '?>>
				<?php if ($c->photo): ?>
					<?= CHtml::image($c->photoUrl, 'Врач',array('class'=>'expertsLogo'))?>
				<? else: ?>
					<?php if ($c->sex->order == 0): ?>
						<?= CHtml::image($this->assetsImageUrl . '/staff-m.jpg', 'Врач',array('class'=>'expertsLogo'))?>
					<? else: ?>
						<?= CHtml::image($this->assetsImageUrl . '/staff-f.jpg', 'Врач',array('class'=>'expertsLogo'))?>
					<? endif; ?>
				<? endif; ?>
				
				<span><?=$c->name?></span>
				</div>
			<?php endforeach;?>
		<?php endif; ?>
	</div>
	<div class="checked_clients">
		<?php if($importDoctors): ?>
			<?php foreach($importDoctors as $c): ?>
				<div data-cid="<?=$c->link?>" class="pexpert">
					<?php if ($c->photo): ?>
						<?= CHtml::image($c->photoUrl, 'Врач',array('class'=>'expertsLogo'))?>
					<? else: ?>
						<?php if ($c->sex->order == 0): ?>
							<?= CHtml::image($this->assetsImageUrl . '/staff-m.jpg', 'Врач',array('class'=>'expertsLogo'))?>
						<? else: ?>
							<?= CHtml::image($this->assetsImageUrl . '/staff-f.jpg', 'Врач',array('class'=>'expertsLogo'))?>
						<? endif; ?>
					<? endif; ?>
					<?=$c->name?>
				</div>
			<?php endforeach;?>
		<?php endif; ?>
	</div>	
	<div class="both"></div>
</div>
<?php
/*
echo CHtml::link('Добавить специалиста', array('experts/add'), array('class' => 'btn'));
echo CHtml::tag('p', array(), Yii::app()->user->getFlash('experts_add'));
$this->widget('zii.widgets.grid.CGridView', array(
	'dataProvider'	 => $dataProvider,
		
	'summaryText'	 => '',
	'itemsCssClass'	 => 'service-table',
	'columns'		 => array(
		array(
			'name'	 => 'ФИО',
			'value'	 => '$data->name',
		),
		array(
			'name'	 => 'Дата рождения',
			'value'	 => 'Yii::app()->dateFormatter->formatDateTime($data->birthday, "medium", null)',
			'type'	 => 'html',
		),
		array(
			'name'	 => 'Пол',
			'value'	 => '$data->sex->name',
		),
		array(
			'name'	 => 'Стаж',
			'value'	 => '$data->experience',
		),
		array(
			'name'	 => 'Специальность',
			'value'	 => 'reset($data->specialties)->name',
			'type'	 => 'html',
		),
		array(
			'class'		 => 'CButtonColumn',
			'template'	 => '{delete}{update}{price}',
			'buttons'	 => array(
				'update' => array(
					'url' => 'CHtml::normalizeUrl(array("experts/update","link"=>$data->link))',
				),
				'delete' => array(
					'url' => 'CHtml::normalizeUrl(array("experts/delete","link"=>$data->link))',
				),
				'price' => array(
					'url' => 'CHtml::normalizeUrl(array("experts/price","link"=>$data->link))',
				),
			),
			'deleteConfirmation' => 'Вы действительно хотите удалить данного врача?'
		),
	),
));*/
?>

protected/modules/adminAll/views/experts/index.php
<div class="flash-error">Внимание! Внесенные изменения появятся на сайте после подтверждения администратором</div>
<? if (Yii::app()->user->hasFlash('experts_add')):?>
<div class="flash-success"><?= Yii::app()->user->getFlash('experts_add')?></div>
<? endif; ?>
<?php
echo CHtml::link('Добавить специалиста', array('experts/add'), array('class' => 'btn'));
?>

<?=CHtml::link('Импорт врачей из другого адреса клиники', array('experts/import'), array('class' => 'btn import_experts'));?>

<br/><br/>

<?php if(true): ?>
<h4>Специалисты из других адресов (редактировать можно в главном адресе)</h4>
<?
	$this->widget('zii.widgets.grid.CGridView', array(
			'id'=>'order-grid2',
			'dataProvider'=>$dataProvider,
			#'filter'=>$oAgrDoctors,
			'enableSorting'=>false,
			'itemsCssClass'	 => 'service-table',
			'summaryText'	 => '',		
			'columns'=>array(
					array(
							'name'=>'name',
							//s'value'=>'$data->name',
					),
					array(
							'name'	 => 'birthday',
							'value'	 => '($data->birthday !== "0000-00-00 00:00:00") ? Yii::app()->dateFormatter->formatDateTime(strtotime($data->birthday), "medium", null) : "Не указана"',
							'type'	 => 'html',
					),
					array(
							'name'	 => 'sexId',
							'value'	 => '$data->sex->name',
					),
					array(
							'name'	 => 'experience',
							'value'	 => '$data->experienceNum',
					),
					array(
							'name'	 => 'specialties.name',
							'value'	 => 'reset($data->specialties)->name',
							#'filter'=>CHtml::activeTextField($oAgrDoctors->doctorSpecialty, 'name'), //CHtml::textField('specialties[name]', $data->specialites->name),
							//'type'	 => 'html',
					),
					/*array(
							'class'		 => 'CButtonColumn',
							'template'	 => '{delete}{update}{price}',
							'buttons'	 => array(
								'update' => array(
									'url' => 'CHtml::normalizeUrl(array("experts/update","link"=>$data->link))',
								),
								'delete' => array(
									'url' => 'CHtml::normalizeUrl(array("experts/delete","link"=>$data->link,"agr"=>1))',
								),
								'price' => array(
									'url' => 'CHtml::normalizeUrl(array("experts/price","link"=>$data->link))',
								),
							),
							'deleteConfirmation' => 'Вы действительно хотите удалить данного врача?'
					),*/
	   ),
	));
?>
<?php endif; ?>


<?php if($oAgrDoctors->search($model)->getData()): ?>
<h4>Неподтвержденные</h4>
<?
	$this->widget('zii.widgets.grid.CGridView', array(
			'id'=>'order-grid2',
			'dataProvider'=>$oAgrDoctors->search($model),
			'filter'=>$oAgrDoctors,
			'enableSorting'=>true,
			'itemsCssClass'	 => 'service-table',
			'summaryText'	 => '',		
			'columns'=>array(
					array(
							'name'=>'name',
							//s'value'=>'$data->name',
					),
					array(
							'name'	 => 'birthday',
							'value'	 => '($data->birthday !== "0000-00-00 00:00:00") ? Yii::app()->dateFormatter->formatDateTime(strtotime($data->birthday), "medium", null) : "Не указана"',
							'type'	 => 'html',
					),
					array(
							'name'	 => 'sexId',
							'value'	 => '$data->sex->name',
					),
					array(
							'name'	 => 'experience',
							'value'	 => '$data->experienceNum',
					),
					array(
							'name'	 => 'specialties.name',
							'value'	 => 'reset($data->specialties)->name',
							'filter'=>CHtml::activeTextField($oAgrDoctors->doctorSpecialty, 'name'), //CHtml::textField('specialties[name]', $data->specialites->name),
							//'type'	 => 'html',
					),
					array(
							'class'		 => 'CButtonColumn',
							'template'	 => '{delete}{update}{price}',
							'buttons'	 => array(
								'update' => array(
									'url' => 'CHtml::normalizeUrl(array("experts/update","link"=>$data->link))',
								),
								'delete' => array(
									'url' => 'CHtml::normalizeUrl(array("experts/delete","link"=>$data->link,"agr"=>1))',
								),
								'price' => array(
									'url' => 'CHtml::normalizeUrl(array("experts/price","link"=>$data->link))',
								),
							),
							'deleteConfirmation' => 'Вы действительно хотите удалить данного врача?'
					),


	   ),
	));
?>
<?php endif; ?>

<h4>Подтвержденные</h4>
<?
$this->widget('zii.widgets.grid.CGridView', array(
		'id'=>'order-grid',
		'dataProvider'=>$oDoctors->search($model),
		'filter'=>$oDoctors,
		'enableSorting'=>true,
		'itemsCssClass'	 => 'service-table',
		'summaryText'	 => '',		
		'columns'=>array(
				array(
						'name'=>'name',
						//s'value'=>'$data->name',
				),
				array(
						'name'	 => 'birthday',
						'value'	 => '($data->birthday !== "0000-00-00 00:00:00") ? Yii::app()->dateFormatter->formatDateTime(strtotime($data->birthday), "medium", null) : "Не указана"',
						'type'	 => 'html',
				),
				array(
						'name'	 => 'sexId',
						'value'	 => '$data->sex->name',
				),
				array(
						'name'	 => 'experience',
						'value'	 => '$data->experienceNum',
				),
				array(
						'name'	 => 'specialties.name',
						'value'	 => 'reset($data->specialties)->name',
						'filter'=>CHtml::activeTextField($oDoctors->doctorSpecialty, 'name'), //CHtml::textField('specialties[name]', $data->specialites->name),
						//'type'	 => 'html',
				),
				array(
						'class'		 => 'CButtonColumn',
						'template'	 => '{delete}{update}{price}',
						'buttons'	 => array(
							'update' => array(
								'url' => 'CHtml::normalizeUrl(array("experts/update","link"=>$data->link))',
							),
							'delete' => array(
								'url' => 'CHtml::normalizeUrl(array("experts/delete","link"=>$data->link))',
							),
							'price' => array(
								'url' => 'CHtml::normalizeUrl(array("experts/price","link"=>$data->link))',
							),
						),
						'deleteConfirmation' => 'Вы действительно хотите удалить данного врача?'
				),
				

   ),
));
?>
<?php
/*
echo CHtml::link('Добавить специалиста', array('experts/add'), array('class' => 'btn'));
echo CHtml::tag('p', array(), Yii::app()->user->getFlash('experts_add'));
$this->widget('zii.widgets.grid.CGridView', array(
	'dataProvider'	 => $dataProvider,
		
	'summaryText'	 => '',
	'itemsCssClass'	 => 'service-table',
	'columns'		 => array(
		array(
			'name'	 => 'ФИО',
			'value'	 => '$data->name',
		),
		array(
			'name'	 => 'Дата рождения',
			'value'	 => 'Yii::app()->dateFormatter->formatDateTime($data->birthday, "medium", null)',
			'type'	 => 'html',
		),
		array(
			'name'	 => 'Пол',
			'value'	 => '$data->sex->name',
		),
		array(
			'name'	 => 'Стаж',
			'value'	 => '$data->experience',
		),
		array(
			'name'	 => 'Специальность',
			'value'	 => 'reset($data->specialties)->name',
			'type'	 => 'html',
		),
		array(
			'class'		 => 'CButtonColumn',
			'template'	 => '{delete}{update}{price}',
			'buttons'	 => array(
				'update' => array(
					'url' => 'CHtml::normalizeUrl(array("experts/update","link"=>$data->link))',
				),
				'delete' => array(
					'url' => 'CHtml::normalizeUrl(array("experts/delete","link"=>$data->link))',
				),
				'price' => array(
					'url' => 'CHtml::normalizeUrl(array("experts/price","link"=>$data->link))',
				),
			),
			'deleteConfirmation' => 'Вы действительно хотите удалить данного врача?'
		),
	),
));*/
?>